### PR TITLE
fix: use Nan::Utf8String instead of v8::String::Utf8Value (fixes #37)

### LINKED ISSUE #37: Fails to compile on Node v12.0.0
Looks like #36 fixed the Electron 5 incompatibility problem, but it still doesn't compile on Node v12.0.0 (even though electron 5 uses node 12 there are still some differences in V8, etc.). Attempting to run `npm install diskusage` (in an empty directory) using Node v12.0.0 produces the following error:

```
node_modules\diskusage\src\main.cpp(26): error C2440: '<function-style-cast>': cannot convert from 'v8::Local<v8::Value>' to 'v8::String::Utf8Value' [C:\Users\User\Documents\tmp\node_modules\diskusage\build\diskusage.vcxproj]
  c:\users\User\documents\tmp\node_modules\diskusage\src\main.cpp(26): note: No constructor could take the source type, or constructor overload resolution was ambiguous
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\User\AppData\Roaming\nvm\v12.0.0\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\User\\AppData\\Roaming\\nvm\\v12.0.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\User\Documents\tmp\node_modules\diskusage
gyp ERR! node -v v12.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

### PR DESCRIPTION
**Pull request by jacobq**
It looks like using `Nan::Utf8String` instead of `v8::String::Utf8Value` like we did on [`node-serialport`/#1843](https://github.com/node-serialport/node-serialport/pull/1843/files) will fix #37 (and hopefully not break anything in the process).

```
node_modules\diskusage\src\main.cpp(26): error C2440: '<function-style-cast>': cannot convert from 'v8::Local<v8::Value>' to 'v8::String::Utf8Value' [C:\Users\User\Documents\tmp\node_modules\diskusage\build\diskusage.vcxproj]
  c:\users\User\documents\tmp\node_modules\diskusage\src\main.cpp(26): note: No constructor could take the source type, or constructor overload resolution was ambiguous
```

### CODE REVIEW

**Comment by jduncanator** [comment]
Tested and works back to Node v0.10.48, thanks!
