### ISSUE TITLE
Fails to build on node v12.3.0

### ISSUE THREAD

**Issue by jacobq** [jduncanator/node-diskusage#40]
I'm not sure why, but this module, as well as others, all seem to be failing to build in CI ever since node v12.3.0 shipped today.

<details>
<summary>Output</summary>

```js
$ npm install diskusage

> diskusage@1.1.1 install C:\Users\jacob\Documents\tmp\node_modules\diskusage
> node-gyp rebuild


C:\Users\jacob\Documents\tmp\node_modules\diskusage>if not defined npm_config_node_gyp (node "C:\Users\jacob\AppData\Roaming\nvm\v12.3.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\jacob\AppData\Roaming\nvm\v12.3.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  main.cpp
  diskusage_win.cpp
  win_delay_load_hook.cc
c:\users\jacob\.node-gyp\12.3.0\include\node\node.h(107): fatal error C1083: Cannot open include file: 'util-inl.h': No such file or directory (compiling source file ..\src\main.cpp) [C:\Users\jacob\Documents\tmp\node_modules\diskusage\build\diskusage.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\jacob\AppData\Roaming\nvm\v12.3.0\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jacob\\AppData\\Roaming\\nvm\\v12.3.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\jacob\Documents\tmp\node_modules\diskusage
gyp ERR! node -v v12.3.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\jacob\Documents\tmp\package.json'
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! diskusage@1.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the diskusage@1.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jacob\AppData\Roaming\npm-cache\_logs\2019-05-22T03_07_50_232Z-debug.log
```

</details>

See also #37

**Comment by jacobq** [comment]
Turns out this is a [node problem](https://github.com/nodejs/node/commit/ae8b64df78) -- [should be fixed](https://github.com/nodejs/node/pull/27804) in 12.3.1
