### ISSUE TITLE
Fails to compile on Node v12.0.0

### ISSUE THREAD

**Issue by jacobq** [jduncanator/node-diskusage#37]
Looks like #36 fixed the Electron 5 incompatibility problem, but it still doesn't compile on Node v12.0.0 (even though electron 5 uses node 12 there are still some differences in V8, etc.). Attempting to run `npm install diskusage` (in an empty directory) using Node v12.0.0 produces the following error:

```
node_modules\diskusage\src\main.cpp(26): error C2440: '<function-style-cast>': cannot convert from 'v8::Local<v8::Value>' to 'v8::String::Utf8Value' [C:\Users\User\Documents\tmp\node_modules\diskusage\build\diskusage.vcxproj]
  c:\users\User\documents\tmp\node_modules\diskusage\src\main.cpp(26): note: No constructor could take the source type, or constructor overload resolution was ambiguous
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\User\AppData\Roaming\nvm\v12.0.0\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\User\\AppData\\Roaming\\nvm\\v12.0.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\User\Documents\tmp\node_modules\diskusage
gyp ERR! node -v v12.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

**Comment by fehmer** [comment]
👍

**Comment by jacobq** [comment]
@fehmer Just for kicks, would you try running against [my fork](https://github.com/jacobq/node-diskusage/commit/22901cb27edf4cd8d5b106ac694ee85cb372dc0b) to see if it [fixes it](https://github.com/jduncanator/node-diskusage/pull/38) for you too?

e.g. set `package.json` dependencies like this:
```js
  "diskusage": "jacobq/node-diskusage#22901cb27edf4cd8d5b106ac694ee85cb372dc0b"
```

**Comment by fehmer** [comment]
@jacobq sure. With your branch its compiling fine.

**Comment by jacobq** [comment]
> @jacobq sure. With your branch its compiling fine.

Cool. Now we're just waiting for @jduncanator to have a moment to review and make sure that the change doesn't break compatibility with old (v0.12.x :exclamation:) versions.

**Comment by fehmer** [comment]
checked npm install with your branch;
- 0.12.18 ✅ 
- 6.17.1✅  
- 8.16.0✅ 
- 10.15.3✅  
- 11.14.0✅ 
- 12.0.0✅

**Comment by jduncanator** [comment]
We actually have a compatibility target of Node 0.10 (🙄) I'll give this a test and merge if all good. Cheers!

**Comment by jduncanator** [comment]
Closed, thanks! New package is published on npm.
